esp8266:
    defs:
        - CMAKE_TOOLCHAIN_FILE=../../cmake/esp8266-open-rtos.cmake
        - CMAKE_SYSTEM_NAME=Generic
        - CONFIG_NO_SYS=True
        - FREERTOS=True
        - FREERTOS_MANUAL=True
        - ESP8266_TOOLCHAIN_PATH=~/usr/xtensa
        - ESP8266_OPEN_RTOS_PATH=~/usr/esp-open-rtos

esp32:
    defs:
        - CMAKE_TOOLCHAIN_FILE=../../cmake/esp32.cmake
        - CMAKE_SYSTEM_NAME=Generic
        - CONFIG_NO_SYS=True
        - FREERTOS=True
        - FREERTOS_MANUAL=True
        - ESP32_TOOLCHAIN_PATH=/opt/xtensa-esp32-elf
        - ESP32_IDF_PATH=~/usr/esp-idf

freertos:
    defs:
        - FREERTOS=True
        - CONFIG_NO_SYS=False
        - PORT=unix
        - CMAKE_SYSTEM_NAME=Generic

unix:
    defs:
        - CONFIG_NO_SYS=False
win32:
    defs:
        - CONFIG_NO_SYS=False
        
atmega2560:
    defs:
        - MCU=atmega2560
        - CONFIG_NO_SYS=True
        - CMAKE_SYSTEM_NAME=Generic
        - CMAKE_TOOLCHAIN_FILE=../../cmake/avr.cmake
        - FREERTOS=True
        - FREERTOS_MANUAL=True
        - AVR=True
        - F_CPU=16000000

atmega328:
    defs:
        - MCU=atmega328
        - ARDUINO_UNO=True
        - CONFIG_NO_SYS=True
        - CMAKE_SYSTEM_NAME=Generic
        - CMAKE_TOOLCHAIN_FILE=../../cmake/avr.cmake
        - FREERTOS=True
        - FREERTOS_MANUAL=True
        - AVR=True
        - F_CPU=16000000
